name: FrostedIsles
main: com.FrostedIsles.Comp.Main
version: 1.0
description: The custom coded plugin.
depend: [Factions]
commands:
    stop:
        description: Restart the server.
        usage: /<command>
        aliases: restart
    gmc:
        description: GameMode Creative.
        usage: /<command>
    gms:
        description: GameMode Survival.
        usage: /<command>
    gma:
        description: GameMode Adventure.
        usage: /<command>
    gmsp:
        description: GameMode Spectator.
        usage: /<command>
    setrank:
        description: Sets rank of player.
        usage: /<command>
    reloadconfig:
        description: Reload plugin config files.
        usage: /<command>
    ci:
        description: Clears inventory. 
        usage: /<command>
    fly:
        description: Enables Fly Mode. 
        usage: /<command>
    maintenance:
        description: Maintenance Mode. 
        usage: /<command>
    spawn:
        description: Teleport to the spawn.
        usage: /<command>
        aliases: hub
    shop:
        description: Teleport to the shop.
        usage: /<command>
    apply:
        description: Apply for staff on our server!
        usage: /<command>
    who:
        description: Gets player info!
        usage: /<command>
    report:
        description: Report an player!
        usage: /<command>
    rtp:
        description: Random teleport!
        usage: /<command>
        aliases: wild
    invsee:
        description: See Inventory!
        usage: /<command>
    broadcaster:
        description: Main broadcaster command!
        usage: /<command>    
    home:
        description: Teleport to your home!
        usage: /<command>    
    homes:
        description: Get a list of your homes!
        usage: /<command>       
    sethome:
        description: Set your home!
        usage: /<command>    
    delhome:
        description: Delete your home!
        usage: /<command>
    warp:
        description: Teleport to a specific location!
        usage: /<command>
    warps:
        description: Get a list of available warps!
        usage: /<command>    
    setwarp:
        description: Set a warp!
        usage: /<command>    
    delwarp:
        description: Delete a warp!
        usage: /<command>    
    kit:
        description: Get a kit!
        usage: /<command>    
    kits:
        description: Get a list of available kits!
        usage: /<command>    
    addkit:
        description: Add a kit to the list of available kits!
        usage: /<command>    
    delkit:
        description: Delete a kit!
        usage: /<command>
    msg:
        description: Message a player!
        usage: /<command>
        aliases: []